name: KabanaManopla
version: '${project.version}'
main: com.github.natanfoleto.kabanamanopla.KabanaManopla
api-version: 1.8.8
softdepend:
  - HolographicDisplays
authors:
  - NatanFoleto
  - Swagviper
commands:
  gauntlet:
    aliases: [manopla]
  givejewel:
    aliases: [darjoia, givejoia]
  activatejewel:
    aliases: [ativarjoia, activatejoia]
  deactivatejewel:
    aliases: [desativarjoia, deactivatejoia]
  kabanamanopla:
    aliases: [manoplareload, reloadmanopla]
