# Configurações do KabanaManopla

# Placeholders
##
# {name} = Nome do jogador (Para mensagens do chat)
# {player} = Nome do jogador (Para comandos executados)

Database:
  Type: "SQLITE" # [SQLITE, MYSQL]
  Sqlite:
    Filename: "database.db"
  Host: "localhost:3306"
  Database: "kabana"
  User: "root"
  Password: "kabana2023"

Joia:
  # Tempo que o jogador precisará esperar para ativar uma jóia específica novamente
  # Em minutos
  DelayAtivarNovamente: 5
  # Exibe ou não, um title ao jogador quando ele ativar uma jóia
  # Mensagem de title configurável em messages.yml (Joia>TitleAtivou, Joia>SubtitleAtivou)
  Title: true

# Ações para quando um jogador completar todas as jóias
EstalarDeDedos:
  Buff:
    # Comandos executados ao ativar todas as jóias
    # Ativar: [] - Para desativar essa opção
    Ativar:
      - coins give {player} 100
    # Comandos executados ao não ter mais todas as jóias ativadas
    # Desativar: [] - Para desativar essa opção
    Desativar:
      - coins remove {player} 100
  Animacoes:
    # Anuncia para todos os jogadores, configurável em messages.yml (EstalarDeDedos>Anuncio)
    Anuncio: true
    # Exibe um title, configurável em messages.yml (EstalarDeDedos>TitleCompletou)
    Title: true
    # Lança um raio no jogador
    Raio: true

